//*************************************************************
//DEFINE PLANETS (Stars, Moons and deferents conunt as planets)
//*************************************************************

//DEFINE TIME CONSTANTS
const yearLength = 365.2425
const earthRotations = 366.2425


const sDay = 1/yearLength;
const sYear = sDay*365
const sMonth = sDay*30;
const sWeek = sDay*7;
const sHour = sDay/24;
const sMinute = sHour/60;
const sSecond = sMinute/60;


var earth = {
  name: "Earth",
  size: 4,   
  color: 0x578B7C,
  sphereSegments: 320,
  startPos: 0,    
  speed: -Math.PI*2/25344,
  rotationSpeed: Math.PI*2*earthRotations,
  tilt: -23.439062,
  tiltb: 0.26,
  orbitRadius: 37.8453,
  orbitCentera: 0,
  orbitCenterb: 0,
  orbitCenterc: 0,
  
  orbitTilta: 0,
  orbitTiltb: 0,  

  textureUrl: 'https://raw.githubusercontent.com/pholmq/tsnova-resources/master/EarthDay.jpg',
  visible: true,
  containerObj:"",
  orbitObj:"",
  planetObj:"",
  pivotObj:"",
  axisHelper: true,
  
  traceLength : sYear * 18,
  traceStep : sDay,
  traceOn: false,
  traceLine: false,
  traceStartPos : 0,
  traceCurrPos : 0,
  traceArrIndex : 0,
};
var moonDef = {
  name: "Moon deferent A",
  size: 0.6 ,
  color: 0x8b8b8b,
  startPos: 227.35,
  speed: 0.71018840177343,
  tilt: 0,
  orbitRadius:0.0279352315075,
  orbitCentera: -0.2,
  orbitCenterb: 0.1,
  orbitCenterc: 0,
  orbitTilta: 0.1,
  orbitTiltb: 0.2,

  visible: false,
  containerObj:"",
  orbitObj:"",
  planetObj:"",
  pivotObj:"",
  axisHelper: false,
  isDeferent: true,
}; 

var moonDefB = {
  name: "Moon deferent B",
  size: 0.6 ,
  color: 0x8b8b8b,
  startPos: -3,
  speed:0,
  tilt: 0,
  orbitRadius: 0,
  orbitCentera: 0.1,
  orbitCenterb: 0.2,
  orbitCenterc: -0.03,
  orbitTilta: 2.3,
  orbitTiltb: 2.6,

  visible: false,
  containerObj:"",
  orbitObj:"",
  planetObj:"",
  pivotObj:"",
  axisHelper: false,
  isDeferent: true,
}; 


var moon = {
  name: "Moon",
  size: 1,
  color: 0x8b8b8b,
  startPos: 260.8,
  speed: 83.28517,
  rotationSpeed: 0,
  tilt: 0,
  orbitRadius: 10,
  orbitCentera: 0.4,
  orbitCenterb: -0.9,
  orbitCenterc: 0,
  orbitTilta: -1.8,
  orbitTiltb: -2.6,

  textureUrl: 'https://raw.githubusercontent.com/pholmq/tsnova-resources/master/Moon.jpg',
  visible: true,
  containerObj:"",
  orbitObj:"",
  planetObj:"",
  pivotObj:"",
  axisHelper: true,
  
  traceLength : sYear * 18,
  traceStep : sDay,
  traceOn: false,
  traceLine: false,
  traceStartPos : 0,
  traceCurrPos : 0,
  traceArrIndex : 0,
};

var sunDef = {
  name: "Sun deferent",
  size: 2 ,
  color: 0xFEAA0D,
  startPos: 0,
  speed:0,
  tilt: 0,
  orbitRadius: 0,
  orbitCentera: 1.4,
  orbitCenterb: 0,
  orbitCenterc: 0,
  orbitTilta: 0,
  orbitTiltb: 0,

  visible: false,
  containerObj:"",
  orbitObj:"",
  planetObj:"",
  pivotObj:"",
  axisHelper: false,
  isDeferent: true,
};

var sun = {
  name: "Sun",
  size: 5,    
  //color: 0xFEAA0D,
  color: 0xFFFF00,
  startPos: 0.1,    
  speed: Math.PI*2,
  rotationSpeed: 83.995,
  tilt: 0,
  orbitRadius: 100,
  orbitCentera: 1.6,
  orbitCenterb: -0.79,
  orbitCenterc: 0,
  orbitTilta: 0.25,
  orbitTiltb: 0,  
  textureUrl: 'https://raw.githubusercontent.com/pholmq/tsnova-resources/master/Sun.jpg',
  textureTransparency: 9,
  visible: true,
  emissive: true,
  containerObj:"",
  orbitObj:"",
  planetObj:"",
  pivotObj:"",
  axisHelper: true,

  traceLength : sYear * 25000,
  traceStep : sYear*10,
  traceOn: false,
  traceLine: false,
  traceStartPos : 0,
  traceCurrPos : 0,
  traceArrIndex : 0,
};

var mercuryDef = {
  name: "Mercury def A",
  size: 0.7,
  color: 0x868485,
  startPos: 0,
  speed: Math.PI*2,
  tilt: 0,
  orbitRadius: 100,
  orbitCentera: -9,
  orbitCenterb: 1.1,
  orbitCenterc: -0.1,
  orbitTilta: 0.6,
  orbitTiltb: 0,

  visible: false,
  containerObj:"",
  orbitObj:"",
  planetObj:"",
  pivotObj:"",
  axisHelper: false,
  isDeferent: true,
};

var mercuryDefB = {
  name: "Mercury def B",
  size: 0.7,
  color: 0x868485,
  startPos: 17.3,
  speed: -6.283185307179586,
  tilt: 0,
  orbitRadius: 0,
  orbitCentera: 0,
  orbitCenterb: 0.4,
  orbitCenterc: 0,
  orbitTilta: -1.5,
  orbitTiltb: 0.6,

  visible: false,
  containerObj:"",
  orbitObj:"",
  planetObj:"",
  pivotObj:"",
  axisHelper: false,
  isDeferent: true,
};

var mercury = {
  name: "Mercury",
  size: 1.4,
  color: 0x868485,
  startPos:-164.7,
  speed: 26.087623,
  tilt: 0,
  orbitRadius: 38.710225,
  orbitCentera:1.2,
  orbitCenterb: -1.2,
  orbitCenterc: 0,
  orbitTilta: 4,
  orbitTiltb: 1.3, 

  textureUrl: 'https://raw.githubusercontent.com/pholmq/tsnova-resources/master/Mercury.jpg',
  visible: true,
  containerObj:"",
  orbitObj:"",
  planetObj:"",
  pivotObj:"",
  axisHelper: true,

  traceLength : sYear * 14,
  traceStep : sDay,
  traceOn: false,
  traceLine: false,
  traceStartPos : 0,
  traceCurrPos : 0,
  traceArrIndex : 0,
};


var venusDef = {
  name: "Venus deferent A",
  size: 2,
  color: 0xA57C1B,
  startPos: 0,
  speed: Math.PI*2,
  tilt: 0,
  orbitRadius: 100,
  orbitCentera: 1.66,
  orbitCenterb: -0.15,
  orbitCenterc: 0,
  orbitTilta: 0,
  orbitTiltb: -0.15,

  visible: false,
  containerObj:"",
  orbitObj:"",
  planetObj:"",
  pivotObj:"",
  axisHelper: true,
  isDeferent: true,
};

var venusDefB = {
  name: "Venus deferent B",
  size: 2,
  color: 0xA57C1B,
  startPos: 13,
  speed: -6.283185307179586,
  tilt: 0,
  orbitRadius: 0,
  orbitCentera: 0,
  orbitCenterb: -0.15,
  orbitCenterc: 0.2,
  orbitTilta: 0,
  orbitTiltb: 0.3,

  visible: false,
  containerObj:"",
  orbitObj:"",
  planetObj:"",
  pivotObj:"",
  axisHelper: true,
  isDeferent: true,
};

var venus = {
  name: "Venus",
  size: 3.9,
  color: 0xA57C1B,
  startPos:-20.7,
  speed: 10.2133116,
  //10.213454 - twoPI
  // speed: 10.213454,
  //speed: 41197.22326*twoPI/TGY,
  tilt: 0,
  orbitRadius: 72.327789,
  orbitCentera: 0,
  orbitCenterb: -0.15,
  orbitCenterc: 0.15,
  orbitTilta: 3.4,
  orbitTiltb: 0,
  traceLength : sYear *16,
  traceStep : sWeek,

  textureUrl: 'https://raw.githubusercontent.com/pholmq/tsnova-resources/master/VenusAtmosphere.jpg',
  visible: true,
  containerObj:"",
  orbitObj:"",
  planetObj:"",
  pivotObj:"",
  axisHelper: true,

  traceOn: false,
  traceLine: false,
  traceStartPos : 0,
  traceCurrPos : 0,
  traceArrIndex : 0,
};

var marsDef = {
  name: "Mars E deferent",
  size: 2,
  color: 0x008000,
  startPos: 0.45,
  speed: 6.283185307179586,
  tilt: 0,
  orbitRadius: 100 ,
  orbitCentera: 12,
  orbitCenterb: -20.5,
  orbitCenterc: -0.5,
  orbitTilta: -1.45,
  orbitTiltb: 0.5,

  visible: false,
  containerObj:"",
  orbitObj:"",
  planetObj:"",
  pivotObj:"",
  isDeferent: true,
}; 

var marsSunDef = {
  name: "Mars S deferent",
  size: 2,
  color: 0xFEAA0D,
  startPos: -99.7,
  speed: 0.398150316,
  tilt: 0,
  orbitRadius: 7.44385 ,
  orbitCentera: -0.2,
  orbitCenterb: -0.7,
  orbitCenterc: 0,
  orbitTilta: -0.1,
  orbitTiltb: -0.325,

  visible: false,
  containerObj:"",
  orbitObj:"",
  planetObj:"",
  pivotObj:"",
  isDeferent: true,
}; 

var mars = {
  name: "Mars",
  size: 2.12,
  color: 0xFF0000,
  startPos: 104,
  //speed: 3.34,
  speed: -3.3406209,
  rotationSpeed: 0,
  tilt: 0,
  orbitRadius: 152.677,
  orbitCentera: 0.2,
  orbitCenterb: -1.5,
  orbitCenterc: 0,
  orbitTilta:-0.4,
  orbitTiltb: -2.2,
  traceLength : sYear * 44,
  traceStep : sWeek, 

  textureUrl: 'https://raw.githubusercontent.com/pholmq/tsnova-resources/master/Mars.jpg',
  visible: true,
  containerObj:"",
  orbitObj:"",
  planetObj:"",
  pivotObj:"",
  axisHelper: true,

  traceOn: true,
  traceLine: false,
  traceStartPos : 0,
  traceCurrPos : 0,
  traceArrIndex : 0,
};

var phobos = {
  name: "Phobos",
  size: 0.5,   
  color: 0x8b8b8b,
  startPos: 122,    
  speed: 6986.5,
  rotationSpeed: 0,
  tilt: 0,
  orbitRadius: 5,
  orbitCentera: 0,
  orbitCenterb: 0,
  orbitCenterc: 0,
  orbitTilta: 0,
  orbitTiltb: 0,

  visible: false,
  containerObj:"",
  orbitObj:"",
  planetObj:"",
  pivotObj:"",
};

var deimos = {
  name: "Deimos",
  size: 0.5,   
  color: 0x8b8b8b,
  startPos: 0,    
  speed: 1802,
  rotationSpeed: 0,
  tilt: 0,
  orbitRadius: 10,
  orbitCentera: 0,
  orbitCenterb: 0,
  orbitCenterc: 0,
  orbitTilta: 0,
  orbitTiltb: 0,

  visible: false,
  containerObj:"",
  orbitObj:"",
  planetObj:"",
  pivotObj:"",
};

var jupiterDef = {
  name: "Jupiter deferent",
  size: 1,   
  color: 0xCDC2B2,
  startPos: 5,    
  speed:-6.283185307179586,
  rotationSpeed: 0,
  tilt: 0,

  orbitRadius: 15,
  orbitCentera: 2,
  orbitCenterb: 0,
  orbitCenterc: 0,
  orbitTilta: -0.25,
  orbitTiltb: 0.4,
  
  visible: false,
  containerObj:"",
  orbitObj:"",
  planetObj:"",
  pivotObj:"",
  isDeferent: true,
};


var jupiter = {
  name: "Jupiter",
  size: 7.5,   
  color: 0xCDC2B2,
  startPos: 36.5,    
  speed: 0.529908,
  rotationSpeed: 0,
  tilt: 0,
  orbitRadius: 520.4,
  orbitCentera: -25,
  orbitCenterb: -45,
  orbitCenterc: 0,
  orbitTilta: 0.9,
  orbitTiltb: -0.7,
  traceLength : sYear * 18,
  traceStep : sWeek,
  
  textureUrl: 'https://raw.githubusercontent.com/pholmq/tsnova-resources/master/Jupiter.jpg',
  visible: true,
  containerObj:"",
  orbitObj:"",
  planetObj:"",
  pivotObj:"",
  axisHelper: true,

  traceOn: false,
  traceLine: false,
  traceStartPos : 0,
  traceCurrPos : 0,
  traceArrIndex : 0,
};
var saturnusDef = {
  name: "Saturn deferent",
  size: 1,   
  color: 0xA79662,
  startPos: 160.5,    
  speed: -6.283185307179586,
  rotationSpeed: 0,
  tilt: 0,
  orbitRadius: 20,
  orbitCentera: 17,
  orbitCenterb: 15,
  orbitCenterc: 0,
  orbitTilta: 0.45,
  orbitTiltb: -0.4,

  visible: false,
  containerObj:"",   


  
  orbitObj:"",
  planetObj:"",
  pivotObj:"",
  isDeferent: true,
};

var saturnus = {
  name: "Saturn",
  size: 6.5,   
  color: 0xA79662,
  startPos: 232.85,    
  speed: 0.213524,
  rotationSpeed: 0,
  tilt: 0,
  orbitRadius: 958.2,
  orbitCentera: 50,
  orbitCenterb: 35,
  orbitCenterc: 0,
  orbitTilta: -1.8,
  orbitTiltb: 0.3,
  traceLength : sYear * 45,
  traceStep : sWeek,

  textureUrl: 'https://raw.githubusercontent.com/pholmq/tsnova-resources/master/Saturn.jpg',
  ringUrl: 'https://raw.githubusercontent.com/pholmq/tsnova-resources/master/saturn-rings.png',
  ringSize: 10,
  visible: true,
  containerObj:"",
  orbitObj:"",
  planetObj:"",
  pivotObj:"",
  axisHelper: true,

  traceOn: false,
  traceLine: false,
  traceStartPos : 0,
  traceCurrPos : 0,
  traceArrIndex : 0,
};

var uranusDef = {
  name: "Uranus deferent",
  size: 1,   
  color: 0xD2F9FA,
  startPos: 108.5,    
  speed: -6.283185307179586,
  rotationSpeed: 0,
  tilt: 0,
  orbitRadius: 20
  ,
  orbitCentera: -11,
  orbitCenterb: 11,
  orbitCenterc: 0,
  orbitTilta: 0.7,
  orbitTiltb: 0,

  visible: false,
  containerObj:"",
  orbitObj:"",
  planetObj:"",
  pivotObj:"",
  isDeferent: true,
};


var uranus = {
  name: "Uranus",
  size: 7.5,   
  //color: 0xCDC2B2,
  color: 0xD2F9FA,
  //2B383A
  startPos: 384.6,    
  speed:0.0747998,
  rotationSpeed: 0,
  tilt: 0,
  orbitRadius: 1920.13568,
  orbitCentera: 60,
  orbitCenterb: -22,
  orbitCenterc: 0,
  orbitTilta: -0.5,
  orbitTiltb: -0.45,
  traceLength : sYear * 18,
  traceStep : sWeek,
  
  textureUrl: 'https://raw.githubusercontent.com/pholmq/tsnova-resources/master/Uranus.jpg',
  visible: true,
  containerObj:"",
  orbitObj:"",
  planetObj:"",
  pivotObj:"",
  axisHelper: true,
  traceOn: false,
  traceLine: false,
  traceStartPos : 0,
  traceCurrPos : 0,
  traceArrIndex : 0,
};

var neptuneDef = {
  name: "Neptune deferent",
  size: 1,   
  color: 0x5E93F1,
  startPos: 175.2,    
  speed: -6.283185307179586,
  rotationSpeed: 0,
  tilt: 0,
  orbitRadius: 20
  ,
  orbitCentera: 0,
  orbitCenterb: 0,
  orbitCenterc: 0,
  orbitTilta: 0,
  orbitTiltb: 0,

  visible: false,
  containerObj:"",
  orbitObj:"",
  planetObj:"",
  pivotObj:"",
  isDeferent: true,
};


var neptune = {
  name: "Neptune",
  size: 7.5,   
  color: 0x5E93F1,
  startPos: 329.3,    
  speed:0.0380799,
  rotationSpeed: 0,
  tilt: 0,
  orbitRadius: 3004.72,
  orbitCentera: 0,
  orbitCenterb: 20,
  orbitCenterc: 0,
  orbitTilta: -1.5,
  orbitTiltb: 1.15,
  traceLength : sYear * 18,
  traceStep : sWeek,
  
  textureUrl: 'https://raw.githubusercontent.com/pholmq/tsnova-resources/master/Neptune.jpg',
  visible: true,
  containerObj:"",
  orbitObj:"",
  planetObj:"",
  pivotObj:"",
  axisHelper: true,

  traceOn: false,
  traceLine: false,
  traceStartPos : 0,
  traceCurrPos : 0,
  traceArrIndex : 0,
};

var halleysDef = {
  name: "Halleys deferent",
  size: 1,   
  color: 0xA57C1B,
  startPos: 192,    
  speed: -6.283185307179586,
  rotationSpeed: 0,
  tilt: 0,
  orbitRadius: 20
  ,
  orbitCentera: -7,
  orbitCenterb: 3,
  orbitCenterc: 12,
  orbitTilta: 0,
  orbitTiltb: 0,

  visible: false,
  containerObj:"",
  orbitObj:"",
  planetObj:"",
  pivotObj:"",
  isDeferent: true,
};


var halleys = {
  name: "Halleys",
  size: 2,   
  color: 0x00FF00,
  planetColor: 0xFFFFFF,
  startPos: 75.25,    
  speed:-0.08301,
  rotationSpeed: 0,
  tilt: 0,
  orbitRadius: 1674.5,
  orbitCentera: -1524,
  orbitCenterb: -230,
  orbitCenterc: -509,
  orbitTilta: 7,
  orbitTiltb: 18.41,
  traceLength : sYear * 90,
  traceStep : sWeek,
  
  visible: false,
  containerObj:"",
  orbitObj:"",
  planetObj:"",
  pivotObj:"",
  axisHelper: true,

  traceOn: false,
  traceLine: false,
  traceStartPos : 0,
  traceCurrPos : 0,
  traceArrIndex : 0,
};

var erosDef = {
  name: "Eros deferent A",
  size: 2,
  color: 0xA57C1B,
  startPos: 0,
  speed: Math.PI*2,
  tilt: 0,
  orbitRadius: 100,
  orbitCentera: 1.66,
  orbitCenterb: -0.15,
  orbitCenterc: 0,
  orbitTilta: 0,
  orbitTiltb: -0.15,

  visible: false,
  containerObj:"",
  orbitObj:"",
  planetObj:"",
  pivotObj:"",
  axisHelper: true,
  isDeferent: true,
};

var erosDefB = {
  name: "Eros deferent B",
  size: 2,
  color: 0xA57C1B,
  startPos: 13,
  speed: -6.283185307179586,
  tilt: 0,
  orbitRadius: 0,
  orbitCentera: 0,
  orbitCenterb: -0.15,
  orbitCenterc: 0.2,
  orbitTilta: 0,
  orbitTiltb: 0.3,

  visible: false,
  containerObj:"",
  orbitObj:"",
  planetObj:"",
  pivotObj:"",
  axisHelper: true,
  isDeferent: true,
};

var eros = {
  name: "Eros",
  size: 3.9,
  color: 0xA57C1B,
  startPos:-20.7,
  speed: 10.2133116,
  //10.213454 - twoPI
  // speed: 10.213454,
  //speed: 41197.22326*twoPI/TGY,
  tilt: 0,
  orbitRadius: 72.327789,
  orbitCentera: 0,
  orbitCenterb: -0.15,
  orbitCenterc: 0.15,
  orbitTilta: 3.4,
  orbitTiltb: 0,
  traceLength : sYear *16,
  traceStep : sWeek,

  visible: false,
  containerObj:"",
  orbitObj:"",
  planetObj:"",
  pivotObj:"",
  axisHelper: true,

  traceOn: false,
  traceLine: false,
  traceStartPos : 0,
  traceCurrPos : 0,
  traceArrIndex : 0,
};
